apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-server-deployment
  labels:
    app: common-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: common-server
  template:
    metadata:
      labels:
        app: common-server
    spec:
      containers:
      - name: common-server
        image: zios07/common-server
        ports:
        - containerPort: 9009
        resources:
          limits:
            cpu: "1"
            memory: "256Mi"
 
---

apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  selector:
    app: common-server
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9009